[package]
name = "wordle-solver"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced", rev = "283d0e7", package = "iced", features = ["lazy"] }

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
strip = true
